version: "3.9"

services:
  appointment-service:
    build: ./appointment-service
    container_name: appointment-service
    env_file:
    - ./appointment-service/.env
    ports:
      - "${APP_PORT}:${APP_PORT}"
    depends_on:
      - nats
      - doctor-service
    environment:
      DATABASE_URL: ${DATABASE_URL}
      DOCTOR_SERVICE_ADDR: ${DOCTOR_SCV_URL}
    networks:
      - app-network

  doctor-service:
    build: ./doctor-service
    container_name: doctor-service
    env_file:
    - ./doctor-service/.env
    environment:
      DATABASE_URL: ${DATABASE_URL}
      NATS_URL: ${NATS_URL}
    ports:
      - "${DOC_PORT}:${DOC_PORT}"
    networks:
      - app-network

  notification-service:
    build: ./notification-service
    container_name: notification-service
    env_file:
    - ./notification-service/.env
    depends_on:
      - nats
    environment:
      NATS_URL: ${NATS_URL}
    networks:
      - app-network

  nats:
    image: nats:2.10
    container_name: nats
    ports:
      - "4222:4222"
    networks:
      - app-network


networks:
  app-network:
    driver: bridge